on:
  release:
    types: [created]

name: Upload Assets

jobs:
  build:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip logo
        run: |
          zip logo.zip logo.svg logo.png

      - name: Zip branding
        run: |
          zip branding.zip  brandmark/* lettermark/* wordmark/* logo.png logo.svg

      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.zip
          file_glob: true
          tag: ${{ github.ref }}
          body: "This is my release text"
