on:
  release:
    types: [created]

name: Upload Assets

jobs:
  build:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip PharmGKB logo
        run: |
          zip logo.zip PharmGKB/logo/logo.svg PharmGKB/logo/logo.png

      - name: Zip PharmGKB branding
        run: |
          zip branding.zip  PharmGKB/brandmark/* PharmGKB/lettermark/* PharmGKB/wordmark/* PharmGKB/logo/*

      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.zip
          file_glob: true
          tag: ${{ github.ref }}
          body: "This is my release text"
